# Data Preparation and Processing in Python Martin Alizée

In [ ]:
# 1. Import libraries
import pandas as pd
import os

# 1. Import the Datasets

In this first step, the two datasets are imported into Python.
The `GAITERITE.csv` file contains gait data collected from the GAITERITE system.
The `RANDO.csv` file contains the randomization information, meaning the group assignment for each patient.
This step is necessary because the information required for the analysis is distributed across two different files.

In [ ]:
# Import walking data
gait = pd.read_csv("data/GAITERITE.csv", sep=";", encoding="latin1")

# Import randomisation data
rando = pd.read_csv("data/RANDO.csv", sep=";", encoding="latin1")

# Displaying the First Rows to Verify the Import
display(gait.head())
display(rando.head())

,NumPAT,CoteChir,Vitesse,Cadence,FAP,Temps de pas (s)GAUCHE,Temps de pas (s)DROITE,Longueur de pas (cm)GAUCHE,Longueur de pas (cm)DROIT,Longueur d'enjambée (cm)GAUCHE,...,Durée du double appui (s)DROIT,Phase oscillante. % du cycleGAUCHE,Phase oscillante. % du cycleDROIT,Phase d'appui. % du cycleGAUCHE,Phase d'appui. % du cycleDROIT,Simple appui. % du cycleGAUCHE,Simple appui. % du cycleDROIT,Double appui. % du cycleGAUCHE,Double appui. % du cycleDROIT,COMMENT
0,NumPAT,CoteChir,Vitesse,Cadence,FAP,TpspasG,TpspasD,LongpasG,LongpasD,LongenjambeeG,...,DureedoubappuiD,PourcentphaoscillG,PourcentphasoscillD,PourcentphasappG,PourcentphasappD,PourcentsimpappuiG,PourcentsimpappuiD,PourcentdoubleappuiG,PourcentdoubleappuiD,.
1,1,G,37.8,61.9,48,1.179,0.79,46.645,27.544,74.09,...,0.889,30.6,22.1,69.5,77.9,21.7,31.2,45.4,46.2,VALIDE
2,2,G,41.8,66.2,51,0.929,0.879,52.554,19.65,74.594,...,0.667,39.3,23.2,60.8,76.8,23.1,39.5,37.7,36.6,VALIDE
3,3,D,28.5,62.1,47,0.8,1.133,9.821,45.263,55.126,...,0.696,13.8,50.1,86.2,49.9,49.4,14,36,36.5,VALIDE
4,4,G,13.5,31.2,47,2.59,1.34,45.49,8.76,54.47,...,2.636,24.3,8.8,75.7,91.2,8.9,24.1,67.6,67.1,VALIDE

   Numpat  RANDOMISATION
0       1              2
1       2              1
2       3              2
3       4              2
4       5              1

# 2. Checking the Columns

Before merging the two datasets, it is important to verify the column names present in each file.
This step helps identify the common column that will be used to link the gait data with the randomization data.

In [ ]:
print("Columns GAITERITE :")
print(gait.columns.tolist())

print("\nColumns RANDO :")
print(rando.columns.tolist())

Colonnes GAITERITE :
['NumPAT', 'CoteChir', 'Vitesse', 'Cadence', 'FAP', 'Temps de pas (s)GAUCHE', 'Temps de pas (s)DROITE', 'Longueur de pas (cm)GAUCHE', 'Longueur de pas (cm)DROIT', "Longueur d'enjambée (cm)GAUCHE", "Longueur d'enjambée (cm)DROITE", 'Durée de la phase oscillante (s)GAUCHE', 'Durée de la phase oscillante (s)DROIT', "Durée de la phase d'appui (s) GAUCHE", "Durée de la phase d'appui (s) DROIT", 'Durée du simple appui (s)GAUCHE', 'Durée du simple appui (s)DROIT', 'Durée du double appui (s)GAUCHE', 'Durée du double appui (s)DROIT', 'Phase oscillante. % du cycleGAUCHE', 'Phase oscillante. % du cycleDROIT', "Phase d'appui. % du cycleGAUCHE", "Phase d'appui. % du cycleDROIT", 'Simple appui. % du cycleGAUCHE', 'Simple appui. % du cycleDROIT', 'Double appui. % du cycleGAUCHE', 'Double appui. % du cycleDROIT', 'COMMENT']

Colonnes RANDO :
['Numpat', 'RANDOMISATION']

# 3. Standardizing Patient Identifier Formats

Both datasets contain a patient identifier, but the column names are not exactly the same: `NumPAT` in the `GAITERITE` dataset and `Numpat` in the `RANDO` dataset.
In addition, Python cannot merge two columns if they are not in the same format.
Therefore, both identifiers are converted into text format to enable the merge.

In [ ]:
# Converting patient identifiers into text format
gait["NumPAT"] = gait["NumPAT"].astype(str)
rando["Numpat"] = rando["Numpat"].astype(str)

# 4. Merging the Two Datasets

The `GAITERITE` and `RANDO` datasets are merged using the patient identifier.
This step makes it possible to obtain a single dataset containing both:
the gait parameters,
and the randomization group of each patient.
The merge is essential in order to compare the mean double support time between the groups.

In [ ]:
# Merging the two datasets
df = pd.merge(gait, rando, left_on="NumPAT", right_on="Numpat")

# Checking the merge
df.head()

,NumPAT,CoteChir,Vitesse,Cadence,FAP,Temps de pas (s)GAUCHE,Temps de pas (s)DROITE,Longueur de pas (cm)GAUCHE,Longueur de pas (cm)DROIT,Longueur d'enjambée (cm)GAUCHE,...,Phase oscillante. % du cycleDROIT,Phase d'appui. % du cycleGAUCHE,Phase d'appui. % du cycleDROIT,Simple appui. % du cycleGAUCHE,Simple appui. % du cycleDROIT,Double appui. % du cycleGAUCHE,Double appui. % du cycleDROIT,COMMENT,Numpat,RANDOMISATION
0,1,G,37.8,61.9,48,1.179,0.79,46.645,27.544,74.09,...,22.1,69.5,77.9,21.7,31.2,45.4,46.2,VALIDE,1,2
1,2,G,41.8,66.2,51,0.929,0.879,52.554,19.65,74.594,...,23.2,60.8,76.8,23.1,39.5,37.7,36.6,VALIDE,2,1
2,3,D,28.5,62.1,47,0.8,1.133,9.821,45.263,55.126,...,50.1,86.2,49.9,49.4,14,36,36.5,VALIDE,3,2
3,4,G,13.5,31.2,47,2.59,1.34,45.49,8.76,54.47,...,8.8,75.7,91.2,8.9,24.1,67.6,67.1,VALIDE,4,2
4,5,G,54.1,85.6,55,0.765,0.637,46.5,29.276,75.23,...,26.7,58.6,73.3,26.7,41.1,31.1,32.3,VALIDE,5,1

# 5. Selecting Valid Data

Not all rows in the dataset are necessarily usable.
The `COMMENT` column indicates whether a measurement is valid or not.
In this step, only observations labeled `VALIDE` are retained.
This selection ensures that the analysis is performed only on reliable data and prevents incorrect measurements from influencing the results.

In [ ]:
# Select valid observations
df = df[df["COMMENT"] == "VALIDE"]

# Checking after filtering
df.head()

,NumPAT,CoteChir,Vitesse,Cadence,FAP,Temps de pas (s)GAUCHE,Temps de pas (s)DROITE,Longueur de pas (cm)GAUCHE,Longueur de pas (cm)DROIT,Longueur d'enjambée (cm)GAUCHE,...,Phase oscillante. % du cycleDROIT,Phase d'appui. % du cycleGAUCHE,Phase d'appui. % du cycleDROIT,Simple appui. % du cycleGAUCHE,Simple appui. % du cycleDROIT,Double appui. % du cycleGAUCHE,Double appui. % du cycleDROIT,COMMENT,Numpat,RANDOMISATION
0,1,G,37.8,61.9,48,1.179,0.79,46.645,27.544,74.09,...,22.1,69.5,77.9,21.7,31.2,45.4,46.2,VALIDE,1,2
1,2,G,41.8,66.2,51,0.929,0.879,52.554,19.65,74.594,...,23.2,60.8,76.8,23.1,39.5,37.7,36.6,VALIDE,2,1
2,3,D,28.5,62.1,47,0.8,1.133,9.821,45.263,55.126,...,50.1,86.2,49.9,49.4,14,36,36.5,VALIDE,3,2
3,4,G,13.5,31.2,47,2.59,1.34,45.49,8.76,54.47,...,8.8,75.7,91.2,8.9,24.1,67.6,67.1,VALIDE,4,2
4,5,G,54.1,85.6,55,0.765,0.637,46.5,29.276,75.23,...,26.7,58.6,73.3,26.7,41.1,31.1,32.3,VALIDE,5,1

# 6. Creating the main variable: Mean Double Support Time

Double support time is measured separately for the left and right sides.
To obtain an overall measure of stability, both values are combined into a single average variable called `DoubleSupport_mean`.
Before the calculation, the columns are converted into numeric format because some values may be read as text due to the use of commas as decimal separators.

In [ ]:
# Converting the left double support column to numeric
df["DoubleSupport_G"] = pd.to_numeric(
    df["Durée du double appui (s)GAUCHE"].astype(str).str.replace(",", "."),
    errors="coerce"
)

# Converting the right double support column to numeric
df["DoubleSupport_D"] = pd.to_numeric(
    df["Durée du double appui (s)DROIT"].astype(str).str.replace(",", "."),
    errors="coerce"
)

# Calculating the mean double support time
df["DoubleSupport_mean"] = (
    df["DoubleSupport_G"] + df["DoubleSupport_D"]
) / 2

# Checking the new variable
df[["NumPAT", "RANDOMISATION", "DoubleSupport_G", "DoubleSupport_D", "DoubleSupport_mean"]].head()

  NumPAT  RANDOMISATION  DoubleSupport_G  DoubleSupport_D  DoubleSupport_mean
0      1              2            0.890            0.889              0.8895
1      2              1            0.690            0.667              0.6785
2      3              2            0.695            0.696              0.6955
3      4              2            2.632            2.636              2.6340
4      5              1            0.436            0.453              0.4445

# 7. Exporting the Clean Dataset

The final dataset is exported under the name `results.csv`.
This file contains the cleaned data, the randomization variable, and the main variable DoubleSupport_mean.
It will then be used in R to perform the descriptive analyses and calculate the effect size.

In [ ]:
# Exporting the clean dataset
df.to_csv("data/results.csv", index=False)