# Préparation et traitement des données sous Python

In [1]:
# 1. Import des bibliothèques
import pandas as pd
import os

# 1. Import des données

Dans cette première étape, les deux bases de données sont importées dans Python.

Le fichier `GAITERITE.csv` contient les données de marche issues du système GAITERITE.  
Le fichier `RANDO.csv` contient les informations de randomisation, c’est-à-dire le groupe auquel appartient chaque patient.

Cette étape est nécessaire car les informations utiles à l’analyse sont réparties dans deux fichiers différents.

In [2]:
# 1. Import des bibliothèques
import pandas as pd
import os

In [3]:
# Importation des données de marche
gait = pd.read_csv("data/GAITERITE.csv", sep=";", encoding="latin1")

# Importation des données de randomisation
rando = pd.read_csv("data/RANDO.csv", sep=";", encoding="latin1")

# Affichage des premières lignes pour vérifier l'importation
display(gait.head())
display(rando.head())

,NumPAT,CoteChir,Vitesse,Cadence,FAP,Temps de pas (s)GAUCHE,Temps de pas (s)DROITE,Longueur de pas (cm)GAUCHE,Longueur de pas (cm)DROIT,Longueur d'enjambée (cm)GAUCHE,...,Durée du double appui (s)DROIT,Phase oscillante. % du cycleGAUCHE,Phase oscillante. % du cycleDROIT,Phase d'appui. % du cycleGAUCHE,Phase d'appui. % du cycleDROIT,Simple appui. % du cycleGAUCHE,Simple appui. % du cycleDROIT,Double appui. % du cycleGAUCHE,Double appui. % du cycleDROIT,COMMENT
0,NumPAT,CoteChir,Vitesse,Cadence,FAP,TpspasG,TpspasD,LongpasG,LongpasD,LongenjambeeG,...,DureedoubappuiD,PourcentphaoscillG,PourcentphasoscillD,PourcentphasappG,PourcentphasappD,PourcentsimpappuiG,PourcentsimpappuiD,PourcentdoubleappuiG,PourcentdoubleappuiD,.
1,1,G,37.8,61.9,48,1.179,0.79,46.645,27.544,74.09,...,0.889,30.6,22.1,69.5,77.9,21.7,31.2,45.4,46.2,VALIDE
2,2,G,41.8,66.2,51,0.929,0.879,52.554,19.65,74.594,...,0.667,39.3,23.2,60.8,76.8,23.1,39.5,37.7,36.6,VALIDE
3,3,D,28.5,62.1,47,0.8,1.133,9.821,45.263,55.126,...,0.696,13.8,50.1,86.2,49.9,49.4,14,36,36.5,VALIDE
4,4,G,13.5,31.2,47,2.59,1.34,45.49,8.76,54.47,...,2.636,24.3,8.8,75.7,91.2,8.9,24.1,67.6,67.1,VALIDE

   Numpat  RANDOMISATION
0       1              2
1       2              1
2       3              2
3       4              2
4       5              1

# 2. Vérification des colonnes

Avant de fusionner les deux bases, il faut vérifier le nom des colonnes présentes dans chaque fichier.

Cette étape permet d’identifier la colonne commune qui servira à associer les données de marche avec les données de randomisation.

In [4]:
print("Colonnes GAITERITE :")
print(gait.columns.tolist())

print("\nColonnes RANDO :")
print(rando.columns.tolist())

Colonnes GAITERITE :
['NumPAT', 'CoteChir', 'Vitesse', 'Cadence', 'FAP', 'Temps de pas (s)GAUCHE', 'Temps de pas (s)DROITE', 'Longueur de pas (cm)GAUCHE', 'Longueur de pas (cm)DROIT', "Longueur d'enjambée (cm)GAUCHE", "Longueur d'enjambée (cm)DROITE", 'Durée de la phase oscillante (s)GAUCHE', 'Durée de la phase oscillante (s)DROIT', "Durée de la phase d'appui (s) GAUCHE", "Durée de la phase d'appui (s) DROIT", 'Durée du simple appui (s)GAUCHE', 'Durée du simple appui (s)DROIT', 'Durée du double appui (s)GAUCHE', 'Durée du double appui (s)DROIT', 'Phase oscillante. % du cycleGAUCHE', 'Phase oscillante. % du cycleDROIT', "Phase d'appui. % du cycleGAUCHE", "Phase d'appui. % du cycleDROIT", 'Simple appui. % du cycleGAUCHE', 'Simple appui. % du cycleDROIT', 'Double appui. % du cycleGAUCHE', 'Double appui. % du cycleDROIT', 'COMMENT']

Colonnes RANDO :
['Numpat', 'RANDOMISATION']

# 3. Mise au même format des identifiants patients

Les deux fichiers possèdent un identifiant patient, mais les noms des colonnes ne sont pas exactement les mêmes : `NumPAT` dans la base GAITERITE et `Numpat` dans la base RANDO.

De plus, Python ne peut pas fusionner deux colonnes si elles ne sont pas au même format.  
Les deux identifiants sont donc transformés en texte afin de permettre la fusion.

In [5]:
# Transformation des identifiants patients en texte
gait["NumPAT"] = gait["NumPAT"].astype(str)
rando["Numpat"] = rando["Numpat"].astype(str)

# 4. Fusion des deux bases de données

Les données GAITERITE et RANDO sont fusionnées à partir de l’identifiant patient.

Cette étape permet d’obtenir une seule base contenant à la fois :
- les paramètres de marche ;
- le groupe de randomisation de chaque patient.

La fusion est indispensable pour pouvoir comparer le temps de double appui moyen entre les groupes.

In [6]:
# Fusion des deux bases
df = pd.merge(gait, rando, left_on="NumPAT", right_on="Numpat")

# Vérification de la fusion
df.head()

,NumPAT,CoteChir,Vitesse,Cadence,FAP,Temps de pas (s)GAUCHE,Temps de pas (s)DROITE,Longueur de pas (cm)GAUCHE,Longueur de pas (cm)DROIT,Longueur d'enjambée (cm)GAUCHE,...,Phase oscillante. % du cycleDROIT,Phase d'appui. % du cycleGAUCHE,Phase d'appui. % du cycleDROIT,Simple appui. % du cycleGAUCHE,Simple appui. % du cycleDROIT,Double appui. % du cycleGAUCHE,Double appui. % du cycleDROIT,COMMENT,Numpat,RANDOMISATION
0,1,G,37.8,61.9,48,1.179,0.79,46.645,27.544,74.09,...,22.1,69.5,77.9,21.7,31.2,45.4,46.2,VALIDE,1,2
1,2,G,41.8,66.2,51,0.929,0.879,52.554,19.65,74.594,...,23.2,60.8,76.8,23.1,39.5,37.7,36.6,VALIDE,2,1
2,3,D,28.5,62.1,47,0.8,1.133,9.821,45.263,55.126,...,50.1,86.2,49.9,49.4,14,36,36.5,VALIDE,3,2
3,4,G,13.5,31.2,47,2.59,1.34,45.49,8.76,54.47,...,8.8,75.7,91.2,8.9,24.1,67.6,67.1,VALIDE,4,2
4,5,G,54.1,85.6,55,0.765,0.637,46.5,29.276,75.23,...,26.7,58.6,73.3,26.7,41.1,31.1,32.3,VALIDE,5,1

# 5. Sélection des données valides

Toutes les lignes du fichier ne sont pas forcément exploitables.  
La colonne `COMMENT` indique si une mesure est valide ou non.

Dans cette étape, seules les observations marquées `VALIDE` sont conservées.

Cette sélection permet de travailler uniquement sur des données fiables et d’éviter que des mesures incorrectes influencent les résultats.

In [7]:
# Sélection des observations valides
df = df[df["COMMENT"] == "VALIDE"]

# Vérification après filtrage
df.head()

,NumPAT,CoteChir,Vitesse,Cadence,FAP,Temps de pas (s)GAUCHE,Temps de pas (s)DROITE,Longueur de pas (cm)GAUCHE,Longueur de pas (cm)DROIT,Longueur d'enjambée (cm)GAUCHE,...,Phase oscillante. % du cycleDROIT,Phase d'appui. % du cycleGAUCHE,Phase d'appui. % du cycleDROIT,Simple appui. % du cycleGAUCHE,Simple appui. % du cycleDROIT,Double appui. % du cycleGAUCHE,Double appui. % du cycleDROIT,COMMENT,Numpat,RANDOMISATION
0,1,G,37.8,61.9,48,1.179,0.79,46.645,27.544,74.09,...,22.1,69.5,77.9,21.7,31.2,45.4,46.2,VALIDE,1,2
1,2,G,41.8,66.2,51,0.929,0.879,52.554,19.65,74.594,...,23.2,60.8,76.8,23.1,39.5,37.7,36.6,VALIDE,2,1
2,3,D,28.5,62.1,47,0.8,1.133,9.821,45.263,55.126,...,50.1,86.2,49.9,49.4,14,36,36.5,VALIDE,3,2
3,4,G,13.5,31.2,47,2.59,1.34,45.49,8.76,54.47,...,8.8,75.7,91.2,8.9,24.1,67.6,67.1,VALIDE,4,2
4,5,G,54.1,85.6,55,0.765,0.637,46.5,29.276,75.23,...,26.7,58.6,73.3,26.7,41.1,31.1,32.3,VALIDE,5,1

# 6. Création de la variable principale : temps de double appui moyen

Le temps de double appui est mesuré séparément à gauche et à droite.

Pour obtenir une mesure globale de stabilité, les deux valeurs sont combinées en une seule variable moyenne : `DoubleSupport_mean`.

Avant le calcul, les colonnes sont converties en format numérique, car certaines valeurs peuvent être lues comme du texte à cause des virgules utilisées comme séparateurs décimaux.

In [8]:
# Conversion de la colonne double appui gauche en numérique
df["DoubleSupport_G"] = pd.to_numeric(
    df["Durée du double appui (s)GAUCHE"].astype(str).str.replace(",", "."),
    errors="coerce"
)

# Conversion de la colonne double appui droit en numérique
df["DoubleSupport_D"] = pd.to_numeric(
    df["Durée du double appui (s)DROIT"].astype(str).str.replace(",", "."),
    errors="coerce"
)

# Calcul du double appui moyen
df["DoubleSupport_mean"] = (
    df["DoubleSupport_G"] + df["DoubleSupport_D"]
) / 2

# Vérification de la nouvelle variable
df[["NumPAT", "RANDOMISATION", "DoubleSupport_G", "DoubleSupport_D", "DoubleSupport_mean"]].head()

  NumPAT  RANDOMISATION  DoubleSupport_G  DoubleSupport_D  DoubleSupport_mean
0      1              2            0.890            0.889              0.8895
1      2              1            0.690            0.667              0.6785
2      3              2            0.695            0.696              0.6955
3      4              2            2.632            2.636              2.6340
4      5              1            0.436            0.453              0.4445

# 7. Export de la base propre

La base finale est exportée sous le nom `results.csv`.

Ce fichier contient les données nettoyées, la variable de randomisation et la variable principale `DoubleSupport_mean`.

Il sera ensuite utilisé dans R pour réaliser les analyses descriptives et le calcul de la taille d’effet.

In [10]:
# Export de la base propre
df.to_csv("data/results.csv", index=False)